language: elixir
elixir:
  - 1.9
otp_release:
  - 22.1.8
cache:
  directories:
    - _build
    - deps
env:
  global:
    - MIX_ENV=test
    - GITHUB_CLIENT_ID=d6fca75c63daa014c187
    - GITHUB_CLIENT_SECRET=8eeb143935d1a505692aaef856db9b4da8245f3c
script:
  - mix do deps.get, compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
